### ISSUE TITLE
Division by Zero in plinkSTR

### ISSUE THREAD

**Issue by bibb** [gymreklab/TRTools#11]
Hello, 

I'm using plinkSTR with a VCF coming from the [STR imputation pipeline](http://gymreklab.com/2018/03/05/snpstr_imputation.html), and I got this error:

Traceback (most recent call last):
  File "/projects/b1049/genetics_programs/gangSTR/bin/plinkSTR", line 11, in <module>
    load_entry_point('strtools==1.0.0', 'console_scripts', 'plinkSTR')()
  File "/projects/b1049/genetics_programs/gangSTR/lib/python3.7/site-packages/strtools-1.0.0-py3.7.egg/plinkSTR/plinkSTR.py", line 354, in main
  File "/projects/b1049/genetics_programs/gangSTR/lib/python3.7/site-packages/strtools-1.0.0-py3.7.egg/plinkSTR/plinkSTR.py", line 112, in PerformAssociation
ZeroDivisionError: float division by zero

I thought maybe it was a problem with my VCF and I tried different chromosomes, different imputed VCFs coming from other cohorts, running the program with different MAF thresholds since line 112 is about that, also with and without covariates, but I got the same error each time. I will appreciate your help in this

Best,  

Bernabe

**Comment by nmmsv** [comment]
can you please check if the latest version of plinkSTR resolves this problem?

**Comment by LiterallyUniqueLogin** [comment]
Closing due to inactivity.
