### ISSUE TITLE
TypeError: vars() argument must have __dict__ attribute

### ISSUE THREAD

**Issue by psychrb** [gymreklab/TRTools#138]
Pls advise: Is the below an ERROR in my input file, or please advise how I might resolve this ERROR, or further check this ERROR...THANKS!

COMMAND LINE:
statSTR --vcf adVNTR_MergedFILE --vcftype advntr --out NEWFILENAME --thresh --afreq --acount --mean --mode --var --numcalled --samples CONT_samples,AFFECTED_samples --sample-prefixes CONT,AFFECTED

ERROR:
Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/py_packages/3.7/bin/statSTR", line 8, in <module>
    sys.exit(run())
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/trtools/statSTR/statSTR.py", line 597, in run
    if args == None:
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/argparse-1.4.0-py3.7.egg/argparse.py", line 1200, in __eq__
    return vars(self) == vars(other)
TypeError: vars() argument must have __dict__ attribute

**Comment by nmmsv** [comment]
Hello,
I just tried several different settings to replicate this error and was not able to do so. Does the error persist?
Is it possible to share the VCF file (or a portion of it) so I can replicate and fix the error on my end?
Thanks.
Nima

**Comment by psychrb** [comment]
Nima, Thanks. I emailed to you. If you prefer that I post on here, please advise...
