### ISSUE TITLE
dumpSTR index error running HipSTR VCF output

### ISSUE THREAD

**Issue by limrock1** [gymreklab/TRTools#143]
Hi,

I ran HipSTR (v0.6.2) on a single TR region (HD on chr4) as follows

HipSTR --bams SAMP1.cram --fasta genome.fa --silent --regions HipSTR.HTT.bed --lib-from-samp \
  --def-stutter-model --max-str-len 1200 --min-reads 15 --output-filters --str-vcf SAMP1.vcf.gz \;
	
I then ran dumpSTR (v4.0.0) with the following command:

dumpSTR --vcf SAMP1.vcf.gz --vcftype hipstr --hipstr-max-call-DP 1000 --hipstr-min-supp-reads 1 \
  --verbose --out SAMP1_L1_filter

and got the following error:

Overwriting the preexisting info AC field
Overwriting the preexisting info REFAC field
Traceback (most recent call last):
  File "/software/miniconda3/bin/dumpSTR", line 8, in <module>
    sys.exit(run())
  File "/software/miniconda3/lib/python3.8/site-packages/trtools/dumpSTR/dumpSTR.py", line 1245, in run
    retcode = main(args)
  File "/software/miniconda3/lib/python3.8/site-packages/trtools/dumpSTR/dumpSTR.py", line 1183, in main
    record = ApplyCallFilters(record, call_filters, sample_info, invcf.samples)
  File "/software/miniconda3/lib/python3.8/site-packages/trtools/dumpSTR/dumpSTR.py", line 569, in ApplyCallFilters
    filt_output = filt(record)
  File "/software/miniconda3/lib/python3.8/site-packages/trtools/dumpSTR/filters.py", line 505, in __call__
    if "/" in record.format["GB"][samples_to_check][0]: delim = "/"
IndexError: index 0 is out of bounds for axis 0 with size 0

Any ideas what might be going on here?
Thanks,
Sean.

**Comment by limrock1** [comment]
K, thanks.

**Comment by LiterallyUniqueLogin** [comment]
TRTools 4.0.1 is out on PyPI and is in the process of being released on bioconda, I'll ping when that's done. Please upgrade and let me know if that fixes the issue.
